# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'learnRAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for learnRAC
   pod 'ReactiveCocoa', '2.5'
  target 'learnRACTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'learnRACUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
